
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost

development:
  <<: *default
  database: tomorrow_development
  username: tomorrow
  password: password1

test:
  <<: *default
  database: tomorrow_test
  username: tomorrow
  password: password1

production:
  <<: *default
  database: tomorrow_production
  username: tomorrow
  password: password3

